name: Documentation

on:
  push:
    paths:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'docs/**'
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate Markdown
        uses: actionshub/markdownlint@main
        with:
          files: README.md, CONTRIBUTING.md
