name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        go mod tidy
        go get github.com/spf13/cobra
        go get github.com/spf13/viper

    - name: Run tests
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
